backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  #name: github
  #repo: edwardnewton/cleanily_static

media_folder: "images/uploads"

publish_mode: editorial_workflow



collections:
  - name: "config"
    label: "Config"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "nav"
        file: "_data/nav.yml"
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Link, name: path, widget: string}
              - {label: Section Id, name: section_id, widget: string}
  - name: "page"
    label: "Page"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    files:
      - file: "index.html"
        label: "Home"
        name: "home"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
          - {label: "Section", name: "section_id", widget: "hidden", default: "home"}
          - {label: Title, name: title, widget: string}
          - {label: "Top Section", name: slides, widget: object, fields: [
              {label: "Banner", name: "banner", widget: "list", fields:[
                {lable: "Bg Image", name: "bg", widget: "image"},
                {lable: "Title", name: "title", widget: "string"},
                {lable: "lists", name: "lists", widget: "list", fields:[
                  {lable: "text", name: "text", widget: "string"}
                ]},
              ]},
              {label: "Forms", name: "forms", widget: "object", fields:[
                {lable: "heading", name: "heading", widget: "string"},
                {lable: "subHeading", name: "subHeading", widget: "string"},
                {lable: "formList", name: "formList", widget: "list", fields:[
                  {lable: "placeholder", name: "placeholder", widget: "string"},
                  {lable: "name", name: "name", widget: "string"},
                  {lable: "type", name: "type", widget: "string"},
                  {lable: "required", name: "required", widget: "Boolean"},
                  {lable: "input", name: "input", widget: "Boolean"}
                ]}
              ]
              }]}
          
          